[workspace]
members = [
  "cli"
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Kevin Schaul <kevin.schaul@gmail.com>"]
license = "MIT"
repository = "https://github.com/kevinschaul/jump-start-tools"
